# Generated by Django 4.1.3 on 2022-11-27 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0005_alter_organisations_license'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload', '0003_share_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='verifyDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_doc', to='upload.share')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_to', models.CharField(max_length=255)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='claimInsurance',
            fields=[
                ('document', models.FileField(upload_to='documents/')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_approved', models.BooleanField(default=False)),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_by', to=settings.AUTH_USER_MODEL)),
                ('request_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim', to='authenticate.organisations')),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_claim', to='upload.share')),
            ],
        ),
    ]
