# Generated by Django 4.1.3 on 2022-11-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_done',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
