# Generated by Django 4.1.3 on 2022-11-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesth',
            name='doc_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requestp',
            name='doc_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
