# Generated by Django 4.1.3 on 2022-11-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_remove_share_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='doc_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
