# Generated by Django 4.1.3 on 2022-11-28 02:16

from django.db import migrations, models
import upload.models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_share_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='document',
            field=models.FileField(upload_to=upload.models.Doc.user_directory_path, validators=[validators.validate_file_size, validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='share',
            name='document',
            field=models.FileField(upload_to=upload.models.Share.user_directory_path, validators=[validators.validate_file_size, validators.validate_file_extension]),
        ),
    ]
