# Generated by Django 4.1.3 on 2022-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='permit',
            field=models.FileField(null=True, upload_to='permits/'),
        ),
    ]
