# Generated by Django 4.1.3 on 2022-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0002_alter_organisations_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='permit',
            field=models.FileField(default=5, upload_to='permits/'),
            preserve_default=False,
        ),
    ]
