# Generated by Django 4.1.3 on 2022-11-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_organisations_permit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='identity_proof',
            field=models.FileField(default=1, upload_to='identity/'),
            preserve_default=False,
        ),
    ]
