# Generated by Django 4.1.3 on 2022-11-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0004_alter_users_identity_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='license',
            field=models.FileField(default=5, upload_to='license/'),
            preserve_default=False,
        ),
    ]
