# Generated by Django 4.1.3 on 2022-11-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0005_alter_organisations_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisations',
            name='org_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
