# Generated by Django 4.1.3 on 2022-11-28 00:34

import authenticate.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0006_organisations_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='identity_proof',
            field=models.FileField(upload_to=authenticate.models.Users.user_directory_path),
        ),
    ]
