# Generated by Django 4.1.3 on 2022-11-28 02:16

import authenticate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0007_user_username_alter_users_identity_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='image1',
            field=models.ImageField(upload_to=authenticate.models.Organisations.user_directory_path2),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='image2',
            field=models.ImageField(upload_to=authenticate.models.Organisations.user_directory_path2),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='license',
            field=models.FileField(upload_to=authenticate.models.Organisations.user_directory_path),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='permit',
            field=models.FileField(upload_to=authenticate.models.Organisations.user_directory_path1),
        ),
    ]
