# Generated by Django 4.1.3 on 2022-11-28 02:23

import authenticate.models
from django.db import migrations, models
import validators


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0008_alter_organisations_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisations',
            name='image1',
            field=models.ImageField(upload_to=authenticate.models.Organisations.user_directory_path2, validators=[validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='image2',
            field=models.ImageField(upload_to=authenticate.models.Organisations.user_directory_path2, validators=[validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='license',
            field=models.FileField(upload_to=authenticate.models.Organisations.user_directory_path, validators=[validators.validate_file_size, validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='organisations',
            name='permit',
            field=models.FileField(upload_to=authenticate.models.Organisations.user_directory_path1, validators=[validators.validate_file_size, validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='users',
            name='identity_proof',
            field=models.FileField(upload_to=authenticate.models.Users.user_directory_path, validators=[validators.validate_file_size, validators.validate_file_extension]),
        ),
    ]
